"""Initial migration.

Revision ID: 5ceaa3adfee5
Revises: 1218596aa270
Create Date: 2022-05-20 11:57:17.882117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ceaa3adfee5'
down_revision = '1218596aa270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('id_book', sa.Integer(), nullable=False))
    op.drop_column('book', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('book', 'id_book')
    # ### end Alembic commands ###
