"""Initial migration.

Revision ID: 914e10a5dcea
Revises: 5ceaa3adfee5
Create Date: 2022-05-20 12:13:21.976730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914e10a5dcea'
down_revision = '5ceaa3adfee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('book', 'author',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'author',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('book', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
