"""Initial migration.

Revision ID: ed23c0c5a39d
Revises: 0aacc6ea25b9
Create Date: 2022-07-15 16:22:07.355650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed23c0c5a39d'
down_revision = '0aacc6ea25b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'author', ['author'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author', type_='unique')
    # ### end Alembic commands ###
